### ISSUE TITLE
Grub reports "unknown filesystem" trying to boot to USB live env

### ISSUE THREAD

**Issue by johnbarney** [itsManjeet/srclang#1]
I love the concept of rlxos and eager to follow it's progress.

I tried to get it installed on my laptop and failed.

Steps:
1. Burned flash drive with both DD and Rufus in ISO mode
2. Boot to USB
3. Select rlx install in grub
4. Grub unable to find /boot/vmlinuz
5. Enter grub cmd line
6. ls informs me (hd0) and (hd1) do not have file systems.
7. Plug USB drive into working machine to sanity check
8. See /boot/vmlinuz hanging out

Clearly there's a module not loading in grub. I tried various insmod commands and never seemed to fix the issue. Decided it was probably more productive to open a ticket. Not sure what other info you might find relevant.

**Comment by itsManjeet** [comment]
You need to burn the flash drive from Rufus in DD mode.
Probably some kernel modules are missing in initrd, I will check them and fix the issue as soon as possible

Some people also facing similar issue,
findfs unable to find LABEL=RLXOS.
