### ISSUE TITLE
Project naming is a huge mistake please reconsider

### ISSUE THREAD

**Issue by timlepes** [itsManjeet/srclang#3]
Both "Source" and "/src" are already ubiquitous concepts in the software development community with an immense force of historical connotation as to what those mean or refer to.  While clever and amusing, on one level, to name your language in such a self-descriptive way, it is also terribly unwise!  You create significant and unnecessary difficulties for yourselves, and your community of developers, because of the inevitable confusion that is going to ensue if you forge ahead with this branding or naming concept.  To search for help on the internet will garner an inordinate number of incorrect results.  Imagine trying to search for help using "Source" or "/src" as your primary search terms.  Can you not see the frustration this will cause?  In conversation, it will be cumbersome as people will need to add language to clarify that they are referring to the language called "Source" and not just any source code irrespective of the language.  It will be cumbersome for those familiar with the language.  And confusing for those not yet familiar with your language.  Why set yourself up for this sort of annoyance?  I don't get it.  The naming joke isn't funny enough to justify the implications.  You want funny naming?  I suggest the famous Abbot & Costello routine, "Who's on first?".  The skit is actually quite illustrative of my point, as it hinges on the confusion caused by unfortunate naming.  But the skit only inflicts levity on it's audience.  Your naming joke will inflict your community in ways that probably aren't worth it.

It's your language, so do what you want.  I'm not personally invested.  But I do think you should at least reconsider what you're doing for the sake of yourselves, and your community.  That's the end of my PSA.  Kind regards and best of luck to you in your endeavor, regardless of whether you change the name or not.  Be well!

**Comment by itsManjeet** [comment]
Ok, that sounds like a valid argument,
actually i am not good at naming things. so, we need to wait until someone suggest a good name or some good name strikes my mind.

**Comment by HaniiPuppy** [comment]
> Ok, that sounds like a valid argument,
> actually i am not good at naming things. so, we need to wait until someone suggest a good name or some good name strikes my mind.

Well if it's for rlxOS, why not something reminiscent of that, using the rlx letters prominently, like "rexLang" or "ralex" or "Rixl"? Something along those lines.

Frankly, almost anything is better than "src" - it's almost self-parodically ungoogleable as a coding language.

**Comment by timlepes** [comment]
I think that HaniiPuppy's suggestion is perfectly reasonable.  It is unique enough to get specific search results, while keeping close to your original naming idea.  Adding "rlx" to the naming makes it reference the main project and is consistent with some of your other naming, like "librlx" or "rlx-init".  Consistency is good!  You can go with "rlxSource" and "/rlxsrc" (or "rlx-Source" and "/rlx-src" if you prefer the hyphenated aesthetic).  Prepending the "rlx" also works from a pronunciation point of view because the "x" sound sort of ends with an "s" sound.  So it flows into the next part of the word ("source") without sounding awkward.  It is easy to say.  I like the "camel-case" variation (capitalized "S", "rlxSource" as opposed to "rlxsource") because it makes the "source" part of the word stand out, and carries forward your initial clever naming scheme without the ambiguity.

Again, it is your project and your language so you can proceed as you see fit.  But I am very happy to see that you are so responsive!  I think it will be good for your project to resolve the naming ambiguity early on.  And, your responsiveness and openness to outside opinion bodes well for your project.  It is a good sign for your future; good to see!  I wish the very best of luck to you!  Be well!

**Comment by itsManjeet** [comment]
Hey thanks,
As i already confirm your arguments as valid.
 "ralex", "rlx-src" sounds much better. and can go with any
